# Generated by Django 3.1.7 on 2021-03-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210313_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
